name: Old CICD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  my-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: cicd
        run: |
          echo "starting pipeline..."
          duration=3000
          sleep $duration
          echo "finished pipeline in $duration"
