name: New CICD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "building"
          duration=45
          sleep $duration
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "testing"
          duration=64
          sleep $duration
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "deploying"
          duration=43
          sleep $duration
