name: Old CICD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "building"
          duration=800
          sleep $duration
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "testing"
          duration=1200
          sleep $duration
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "deploying"
          duration=1000
          sleep $duration
